#!/usr/bin/env fish

if not [ $OS = Mac ]
  echo 'No defaults for this system' >&2
  exit 1
end

defaults write com.googlecode.iterm2 PrefsCustomFolder $XDG_CONFIG_HOME/iterm

defaults write com.apple.dock autohide -int 1

defaults write com.apple.ScriptEditor2 DefaultLanguageType -int 1785946994

defaults write org.m0k.transmission proxy-port 8888
defaults write org.m0k.transmission proxy-server 127.0.0.1
defaults write org.m0k.transmission proxy-server-enabled -bool yes
