set runtimepath+=$HOME/.dotfiles/nvim

runtime plugins-init.vim
runtime general.vim
runtime dragvisuals.vim
runtime sessions.vim
runtime snippets.vim
runtime statusbar.vim
runtime completion.vim
runtime files.vim
runtime history.vim
runtime finding.vim
runtime mappings.vim
runtime git.vim
runtime fuzzy.vim
runtime tmux.vim
runtime clipboard.vim
runtime syntax.vim
runtime colors.vim
runtime dispatching.vim
runtime meta.vim
runtime search.vim
runtime plugins.vim
