#!/usr/bin/env fish

[ $OS = Mac ]; and osascript -l JavaScript -e 'Application("System Events").appearancePreferences.darkMode()' > $dataDir/dark_mode
[ -f $dataDir/dark_mode ]; or echo true > $dataDir/dark_mode

set isDark (cat $dataDir/dark_mode)

if [ $isDark = true ]
  echo 'Dark mode is on' >&2
else
  echo 'Dark mode is off' >&2
end
